const fs = require('fs');
const path = require('path');

const pluginsDir = path.join(__dirname, 'plugins');
const outputFile = path.join(__dirname, 'src', 'loadedPlugins.ts');

let importStatements = '';
let initCalls = '';

fs.readdirSync(pluginsDir).forEach(pluginDir => {
  const pluginPath = path.join(pluginsDir, pluginDir);
  const manifestPath = path.join(pluginPath, 'manifest.json');

  if (fs.existsSync(manifestPath)) {
    const manifest = require(manifestPath);

    if (manifest && manifest.entry) {
      const entryPath = `../plugins/${pluginDir}/${manifest.entry}`;
      const importName = `Plugin_${pluginDir}`;

      importStatements += `import ${importName} from '${entryPath}';\n`;
      initCalls += `  ${importName}.init(pluginRegistry);\n`;
    }
  }
});

const content = `// This file is autogenerated. DO NOT EDIT.

${importStatements}
import {PluginRegistry} from './types/plugin_registry';

export function initPlugins(pluginRegistry: PluginRegistry) {\n${initCalls}}
`;

fs.writeFileSync(outputFile, content);
console.log(`Generated plugin import file at ${outputFile}`);
